app = "privmssg"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/resources/healthcheck"

[vm]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4