# fly.toml app configuration file generated for privmssg on 2024-06-22T14:02:11+02:00
app = "privmssg"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[vm]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4
